version: "3"

networks:
  avanc_network:
    driver: bridge


services:
  service:
    build: avanc-admin
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - static_volume:/opt/app/static
    networks:
      - avanc_network

  database:
    image: postgres:16

    container_name: postgres_avanc
    restart: on-failure
    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - avanc_network

volumes:
  postgres_data:
  static_volume:
